---
- hosts: repository
  user: root
  tasks:
  - name: Create repository root directory
    file: path="{{ splunk_repository.repository_root }}"
          state=directory
  
  - name: Create repository apps directory
    file: path="{{ splunk_repository.repository_root }}/apps"
          state=directory

  - name: Create repository packages directory
    file: path="{{ splunk_repository.repository_root }}/packages"
          state=directory

  - name: Create distServerKeys directory
    file: path="{{ splunk_repository.repository_root }}/distServerKeys"
          state=directory

  - name: Create licenses directory
    file: path="{{ splunk_repository.repository_root }}/licenses"
          state=directory

  - name: Create licenses/enterprise directory
    file: path="{{ splunk_repository.repository_root }}/licenses/enterprise"
          state=directory   

  - name: Set repository owner/group
    file: path={{ splunk_repository.repository_root }} 
          recurse=yes 
          owner={{ splunk_repository.repository_owner }} 
          group={{ splunk_repository.repository_group }}

  - name: Set repository directory mode
    file: path={{ splunk_repository.repository_root }} 
          mode=750

  - name: Find app roles
    command: "ls roles/apps"
    register: app_roles
 
  - name: Create deploy_apps.yml
    template: src=roles/common/templates/deploy_apps.yml.j2
              dest=./deploy_apps.yml
              mode=0640
