---
- name: Clean existing app directory
  file: path="{{ splunk_installation.splunk_home_path }}/etc/{{ item.key | replace('shcluster_apps', 'shcluster/apps') | replace('_', '-') }}/{{ app_name }}"
        state=absent
  when: "item.value.clean_install is defined and
        item.value.clean_install == true and
        item.value.git_repo is defined"
  with_dict: "{{ vars['app_variable'] }} | app_default"

- name: Clone repository 
  git: 
    repo={{ item.value.git_repo }} 
    dest="{{ splunk_installation.splunk_home_path }}/etc/{{ item.key | replace('shcluster_apps', 'shcluster/apps') | replace('_', '-') }}/{{ app_name }}"
    version={{ item.value.git_version | default('HEAD') }}
    clone=yes
    update=no
    force=no
  when: "item.value.install == true and
        item.value.git_repo is defined"
  with_dict: "{{ vars['app_variable'] }} | app_default"
  notify: 
    - splunk_reload_deploy_server
    - splunk_apply_cluster_bundle
    - splunk_apply_shcluster_bundle
