---

- name: Check if passwd file exists
  stat: path={{ splunk_installation.splunk_home_path }}/etc/passwd
  register: has_passwd_file

- name: Change default password
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk edit user admin -password '{{ splunk_installation.admin_password }}' -auth admin:changeme --accept-license"
  when: has_passwd_file.stat.exists == false
