---

- name: Get serverName
  shell: "grep serverName {{ splunk_installation.splunk_home_path }}/etc/system/local/server.conf | cut -c14-"
  register: splunk_servername

- name: Fetch distServerKeys from all Servers
  fetch: src="{{ splunk_installation.splunk_home_path }}/etc/auth//distServerKeys/trusted.pem"
         dest="{{ splunk_repository.repository_root }}/distServerKeys/{{ splunk_servername.stdout }}/trusted.pem"
         flat=yes
         fail_on_missing=yes 
