---

- name: Open splunkd port on firewalld
  firewalld: port="{{ item }}"
             permanent=true
             state=enabled 
  when: splunk_installation.firewalld_open_port is defined
  with_items: splunk_installation.firewalld_open_port | default()
