---

- name: Remove app
  file: path="{{ splunk_installation.splunk_home_path }}/etc/{{ item.key | replace('shcluster_apps', 'shcluster/apps') | replace('_', '-') }}/{{ app_name }}"
        state=absent
  when: "{{ item.value.install }} is defined and
        {{ item.value.install }} == false"
  with_dict: "{{ vars['app_variable'] }} | app_default"
  notify: 
    - splunk reload deploy-server 
    - splunk apply cluster-bundle
    - splunk apply shcluster-bundle
